# Copyright 2020 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence .NET Extend Client GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - v14.1.1.0-net-core
  pull_request:
    types:
      - opened
      - committed
    branches:
    - main
    - v14.1.1.0-net-core

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    # Run Tests
    # - name: Run Tests
    #  run: dotnet test --configuration Release --no-restore

  test:
    # we have to test on Linux in order to use Docker for test server
    name: Test against Coherence ${{ matrix.coherence_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coherence_version: [14.1.1-0-2, 20.06.1]
    services:
      test-server:
        image: docker.pkg.github.com/oracle/coherence-dotnet-extend-client/test-server:${{ matrix.coherence_version }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 9040:9040
          - 9042:9042
          - 9043:9043
          - 9098:9098
          - 9099:9099
          - 9490:9490
          - 9700:9700
          - 9800:9800
          - 9900:9900
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install SSL certificates
    - name: Install SSL certificates
      run: |
        sudo cp tests/Coherence.Core.Tests/Config/testcert.pem /usr/local/share/ca-certificates/testcert.crt
        sudo cp tests/Coherence.Core.Tests/Net/Ssl/CA.cer /usr/local/share/ca-certificates/CA.crt
        sudo cp tests/Coherence.Core.Tests/Net/Ssl/Server.cer /usr/local/share/ca-certificates/Server.crt
        sudo update-ca-certificates
        
    # Build
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    # Run Tests
    - name: Run Tests
      run: dotnet test --configuration Release --no-restore
