# Copyright 2020 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence .NET Extend Client GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: CI Build

on:
  push:
    branches:
    - main
    - v14.1.1.0-net-core
  pull_request:
    types:
      - opened
      - committed
    branches:
    - main
    - v14.1.1.0-net-core
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Restore
    - name: Restore
      run: dotnet restore --configuration Release

    # Build
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Restore
    - name: Restore
      run: dotnet test --configuration Release --no-restore

    # Capture logs and test reports for diagnosing failures
    - name: Capture test logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-output
        path: build\**\*.log

    - name: Capture test reports
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-reports
        path: build\**\*tests.xml
